name: google_map_dart
version: 0.0.3
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: Polymer google-map for Dart
homepage: https://github.com/mattjones.org/google-map-dart
dependencies:
  custom_element_apigen: any
  polymer: any
  core_elements: any
  google_apis:
    path: ../google-apis/
dev_dependencies:
  path: ">=1.0.0 <2.0.0"
transformers:
- polymer:
    lint: false